package com.twinops.backend.analysis.controller;

import com.twinops.backend.analysis.dto.AnalysisReportDto;
import com.twinops.backend.analysis.service.AnalysisService;
import com.twinops.backend.auth.service.AdminAuthGuard;
import com.twinops.backend.common.exception.UnauthorizedException;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

import java.util.List;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@WebMvcTest(AnalysisController.class)
class AnalysisControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @MockBean
    private AnalysisService analysisService;

    @MockBean
    private AdminAuthGuard adminAuthGuard;

    @Test
    void shouldDisableManualCreateReport() throws Exception {
        mockMvc.perform(post("/api/analysis/reports")
                .contentType(MediaType.APPLICATION_JSON)
                .content("""
                    {"deviceCode":"DEV001","metricSummary":"cpu=90"}
                    """))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").value("manual analysis submission is disabled; reports are generated by scheduled automation"));
    }

    @Test
    void shouldListReportsAfterAuthGuardPasses() throws Exception {
        when(analysisService.listReports(5)).thenReturn(List.of(
            new AnalysisReportDto(1L, "DEV001", "cpu=90", "过热风险", 0.92, "high", "检查散热", "success", null, "2026-04-03 12:00:00")
        ));

        mockMvc.perform(get("/api/analysis/reports").param("limit", "5"))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.data.length()").value(1))
            .andExpect(jsonPath("$.data[0].deviceCode").value("DEV001"));

        verify(adminAuthGuard).requireAdmin(any());
    }

    @Test
    void shouldReturn401WhenListReportsUnauthorized() throws Exception {
        doThrow(new UnauthorizedException("admin login required"))
            .when(adminAuthGuard).requireAdmin(any());

        mockMvc.perform(get("/api/analysis/reports"))
            .andExpect(status().isUnauthorized())
            .andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.message").value("admin login required"));
    }

    @Test
    void shouldGetReportDetailAfterAuthGuardPasses() throws Exception {
        when(analysisService.getReport(2L)).thenReturn(
            new AnalysisReportDto(2L, "DEV002", "cpu=80", "中风险", 0.61, "medium", "持续观察", "success", null, "2026-04-03 00:00:00")
        );

        mockMvc.perform(get("/api/analysis/reports/2"))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.data.id").value(2))
            .andExpect(jsonPath("$.data.deviceCode").value("DEV002"));

        verify(adminAuthGuard).requireAdmin(any());
    }
}

